Update vm.yaml
Signed-off-by: Paul Luse <paul.e.luse@intel.com>

diff --git a/.github/workflows/vm.yaml b/.github/workflows/vm.yaml
--- a/.github/workflows/vm.yaml
+++ b/.github/workflows/vm.yaml
@@ -21,17 +21,7 @@ jobs:
           echo "Restoring clean VM image..."
           echo "***************************"
           ls run*
-          MAX_RETRIES=3
-          RETRY_DELAY=5
-          for i in $(seq 1 $MAX_RETRIES); do
-            vagrant ssh -c "vagrant snapshot restore clean_vm_v1"
-            if [ $? -eq 0 ]; then
-              break
-            fi
-            echo "Vagrant SSH command failed. Retrying in $RETRY_DELAY seconds..."
-            sleep $RETRY_DELAY
-          done
-          #vagrant snapshot restore clean_vm_v1
+          vagrant snapshot restore clean_vm_v1
           vagrant ssh -c "sudo sudo timedatectl set-timezone UTC && \
             sudo systemctl restart chronyd && sudo chronyc -a makestep && sleep 1"
           vagrant ssh -c "echo 'Fresh VM, hello world!' && date && uname -r && gcc --version"
@@ -60,7 +50,18 @@ jobs:
           echo "********************************"
           echo "Prepare minimal kernel config..."
           echo "********************************"
-          vagrant ssh -c "cd host/linux && ./config.sh"
+          MAX_RETRIES=3
+          RETRY_DELAY=5
+          for i in $(seq 1 $MAX_RETRIES); do
+            echo "XXXXXXXXX"
+            vagrant ssh -c "cd host/linux && ./config.sh"
+            if [ $? -eq 0 ]; then
+              break
+            fi
+            echo "Vagrant SSH command failed. Retrying in $RETRY_DELAY seconds..."
+            sleep $RETRY_DELAY
+          done
+          #vagrant ssh -c "cd host/linux && ./config.sh"
       - name: Build kernel
         run: |
           cd ../linux
