Update vm.yaml
Signed-off-by: Paul Luse <paul.e.luse@intel.com>

diff --git a/.github/workflows/vm.yaml b/.github/workflows/vm.yaml
--- a/.github/workflows/vm.yaml
+++ b/.github/workflows/vm.yaml
@@ -18,26 +18,19 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Build the project
-        id: build
         run: |
           pwd
           ls -al
           make > out.txt 2>&1
-          echo "XXXXXX"
-          echo $1
         continue-on-error: true
       - name: test stuff
         run: |
           ls -al
-          echo $1
-          if [ $? -ne 0 ]; then
-              echo "FAIL"
-              cat out.txt
-              echo "fail=true" >> "$GITHUB_OUTPUT"
-          else
-              echo "fail=false" >> "$GITHUB_OUTPUT"
+          if [[ ${{ failure() }} == true ]]; then
+            echo "Build FAILED" 
+            cat out.txt
+            exit 1
           fi
-          echo "----------------"
       - name: Send mail
         uses: dawidd6/action-send-mail@v3
         with:
