Update vm.yaml
Signed-off-by: Paul Luse <paul.e.luse@intel.com>

diff --git a/.github/workflows/vm.yaml b/.github/workflows/vm.yaml
--- a/.github/workflows/vm.yaml
+++ b/.github/workflows/vm.yaml
@@ -23,6 +23,9 @@ jobs:
           pwd
           ls -al
           make | tee out.txt
+          if [ $? -eq 0 ]; then
+              echo "FAIL"
+          fi
       #- name: Upload artifacts
       #  uses: actions/upload-artifact@v4
       #  with:
